import fs from "fs";
import { resolve, parse } from "path";
const cwd = process.cwd();

let ignoreWatch = false;

function fixName(p = "") {
  p = p.replace(/\./g, "");
  p = p.replace(/-/g, "_");
  p = p.replace(/\//g, "_");
  return p;
}

function makeFetchCode(exportName, basePath) {
  return `/* eslint-disable */
// Code generated by svelte-zero-api, DO NOT EDIT.

import { createZeroApi } from 'svelte-zero-api';
import type __types from './types';

export const ${exportName} = createZeroApi<typeof __types>({ baseUrl: '/${basePath}' });
`;
}

function makeApiCode(importCode, dirText) {
  return `/* eslint-disable */
// Code generated by svelte-zero-api, DO NOT EDIT.

${importCode}
export default ${dirText}
`;
}

function maketypeCode() {
  return `/* eslint-disable */
  // Code generated by svelte-zero-api, DO NOT EDIT.
  
  import zeroApi from './zero-api';
  
  export default zeroApi;
  `;
}

function updateAPI(realPath = "", createDir) {
  const fixRealPath = (inPath = "") => {
    inPath = inPath.replace(/\.(ts|js)/, "");
    return inPath.replace(realPath, "..");
  };
  let dir = {};
  let importCode = "";
  const loadDir = (thePath, obj) => {
    const files = fs.readdirSync(thePath);
    files.forEach((file) => {
      if (file === createDir) {
        return;
      }
      const p = resolve(thePath, file);
      const stat = fs.statSync(p);
      const key = "'" + file.replace(/\.(ts|js)/, "") + "'";
      if (stat.isDirectory()) {
        if (!obj[key]) {
          obj[key] = {};
        }
        loadDir(p, obj[key]);
      } else if (/\.(ts|js)$/.test(file) && !/\.d\.ts$/.test(file)) {
        const importName = fixRealPath(p);
        const name = fixName(importName);
        importCode += `import * as ${name} from "${importName}";\n`;
        obj[key] = name;
      }
    });
  };
  loadDir(realPath, dir);
  const dirText = JSON.stringify(dir).replace(/\"/g, "");

  ignoreWatch = true;
  fs.writeFile(
    resolve(realPath, createDir + "/zero-api.ts"),
    makeApiCode(importCode, dirText),
    (err) => {
      if (err) {
        console.error(err);
      }
      setTimeout(() => {
        ignoreWatch = false;
      });
    }
  );
}

export default function ({ watchPath, baseUrl, createDir, exportName }) {
  createDir = createDir || "zero-api";
  exportName = exportName || "api";
  const realPath = resolve(cwd, watchPath);

  if (!fs.existsSync(resolve(realPath, createDir))) {
    fs.mkdirSync(resolve(realPath, createDir));
  }

  fs.writeFile(
    resolve(realPath, createDir + "/types.d.ts"),
    maketypeCode(),
    (err) => {
      if (err) {
        console.error(err);
      }
    }
  );

  const basePath = baseUrl || parse(realPath).base;

  fs.writeFile(
    resolve(realPath, createDir + "/index.ts"),
    makeFetchCode(exportName, basePath),
    (err) => {
      if (err) {
        console.error(err);
      }
    }
  );

  updateAPI(realPath, createDir);
  fs.watch(realPath, (event, file) => {
    if (!ignoreWatch) {
      updateAPI(realPath, createDir);
    }
  });
}
