/* eslint-disable */
// Code generated by svelte-zero-api, DO NOT EDIT.

import { createZeroApi } from 'svelte-zero-api';
import type __types from './types';

export const api = createZeroApi<typeof __types>({ baseUrl: '/api' });
