interface StatusCodeFn {
	informational:
	  'continue'
	| 'switchingProtocols' 
	| 'processing' 
	| 'earlyHints'
	success:
	  'ok'
	| 'accepted' 
	| 'nonAuthoritativeInformation' 
	| 'noContent' 
	| 'resetContent' 
	| 'partialContent' 
	| 'multiStatus' 
	| 'alreadyReported' 
	| 'imUsed'
	redirect:
	  'multipleChoices' 
	| 'movedPermanently' 
	| 'found' 
	| 'seeOther' 
	| 'notModified' 
	| 'useProxy' 
	| 'switchProxy' 
	| 'temporaryRedirect' 
	| 'permanentRedirect'
	clientError:
	  'badRequest' 
	| 'unauthorized' 
	| 'paymentRequired' 
	| 'forbidden' 
	| 'notFound' 
	| 'methodNotAllowed' 
	| 'notAcceptable' 
	| 'proxyAuthenticationRequired' 
	| 'requestTimeout' 
	| 'conflict' 
	| 'gone' 
	| 'lengthRequired' 
	| 'preconditionFailed' 
	| 'payloadTooLarge' 
	| 'uriTooLong' 
	| 'unsupportedMediaType' 
	| 'rangeNotSatisfiable' 
	| 'expectationFailed' 
	| 'imATeapot' 
	| 'misdirectedRequest' 
	| 'unprocessableEntity' 
	| 'locked' 
	| 'failedDependency' 
	| 'tooEarly' 
	| 'upgradeRequired' 
	| 'preconditionRequired' 
	| 'tooManyRequests' 
	| 'requestHeaderFieldsTooLarge' 
	| 'unavailableForLegalReasons'
	serverError:
	  'internalServerError' 
	| 'notImplemented' 
	| 'badGateway' 
	| 'serviceUnavailable' 
	| 'gatewayTimeout' 
	| 'httpVersionNotSupported' 
	| 'variantAlsoNegotiates' 
	| 'insufficientStorage' 
	| 'loopDetected' 
	| 'notExtended' 
	| 'networkAuthenticationRequired'
}
